"""
export_figures.py
Converts SVG source files to high-resolution PNG figures.
"""

import cairosvg
import os

FIGURES = [
    ("figures/clusters_en.svg",  "figures/figure1_thematic_clusters.png"),
    ("figures/prisma_en.svg",    "figures/figure2_prisma_flow.png"),
]

if __name__ == "__main__":
    for svg_path, png_path in FIGURES:
        if not os.path.exists(svg_path):
            print(f"  [SKIP] {svg_path} not found")
            continue
        cairosvg.svg2png(url=svg_path, write_to=png_path, scale=2)
        print(f"  [OK] {png_path}")

    print("\nNote: figure3 and figure4 are generated by build_networks.py")
